### PR TITLE
(Update-Metadata) dependency and file updating

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm 
This will update this function with the added ability to change dependency and file areas of the nuspec file.

### CODE REVIEW

**Comment by RedBaron2** [comment]
> I have a few things that need to be updated/added before I can accept this pull request:
  That is fine it is your module function I am editing/updating

> 1. Add examples in the function comment on how the user would use these new additions
These are now added

> 2. Add unit tests for both failing and successful updates, and these unit tests should at a minimum include the following:
😕 I'm to add these test where ??

> 3. What is expected when a file source is updated
> 4. What is expected when someone tries to add a new file source
`Update-Metadata -data @{ file = 'tools\**,tools' }` or `@{ file = 'tools\**,tools' } | Update-Metadata`
Will change this code ` <files><file src="" target="" /></files>`
to this in the nuspec  `<files><file src="tools\**" target=",tools" /></files>`

> 5. What is expected when updating the dependency
> 6. What is expected when someone tries to add a new dependency
`@{ dependency = 'kb2919355,1.0.20160915' } | Update-Metadata` or `Update-Metadata -data @{ dependency = 'kb2919355,1.0.20160915' }`
Will change this code ` <dependencies><dependency id="" version="" /></dependencies>`
to this in the nuspec  ` <dependencies><dependency id="kb2919355" version="1.0.20160915" /></dependencies>`

> 7. Fix the formatting to conform to the existing format used in the repository
Updated to be the same formatting

> 8. Remove the if statement regarding the `$value` check, the keys and value should already have been added to `$data` so there should not be a need to duplicate the effort.
Removed these lines of code

> 9. Re-add the empty lines that were already present, these were added on purpose.
Formatting has been fixed to match

> 10. Fix the commit headers, having them saying `Updated Update-Metadata.ps1` do not tell anyone looking through the commits anything about the changes.
If you can tell me of a easier way to update my first commit comment that would be appreciated.

**Comment by AdmiringWorm** [comment]
> 😕 I'm to add these test where ??

The tests need to be added in: https://github.com/WormieCorp/Wormies-AU-Helpers/blob/develop/tests/public/Update-Metadata.Tests.ps1 (You can create a new file if you feel that is easier).

Regarding point 4-6 should actually have been underneath point 2 (of what unit tests would be expected), unfortunately github markdown parser didn't play nice to me.

> Updated to be the same formatting

Only partially, you also changed spaces to be tabs.

> If you can tell me of a easier way to update my first commit comment that would be appreciated.

Use the git client, then call `git rebase upstream/develop -i` (assuming that you call the remote of this repository upstream), then change the call of `pick` to `edit` to edit the commit messages.
The header of the commits should be a very short summary of the change for the commit (not which file was edited).

> potential mis match of function brackets will fix this tomorrow

Be aware that I will be away for a while with spotty network connection (expected until next Wednesday), so it will be days until I can merge anything in.

I'll investigate regarding the error on appveyor, as it seems to be related to versioning of the module.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Sorry for all the trouble with the PR. I'll work on the tests later. 
I hope it was not my fault for the appveyor error
I'll work on trying to use the git CL, but have never worked with it in the past.

Thanks for taking the time for the reviews so far today 👍

**Comment by AdmiringWorm** [comment]
> Sorry for all the trouble with the PR. I'll work on the tests later.

Don't worry about it, everything is a learning process. I would probably have been more lenient if I had the time today to work on it myself.

> I hope it was not my fault for the appveyor error

It wasn't, it was an oversight on my part when it comes to the naming of pull requests.

> I'll work on trying to use the git CL, but have never worked with it in the past.

You can also use a GUI program if you don't like the CLI, like the github GUI client, smartgit, and so on.
I haven't used them in a year or so, so I don't know how up to scratch they are right now (I prefer CLI commands).

**Comment by AdmiringWorm** [comment]
@RedBaron2 thank you for adding the unit tests,

there is a couple of unit tests that are missing and need to be added.

These are regarding adding new dependencies (in the case where there isn't any matching `<dependency` element), and the same for the files.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I thought about adding those tests, but the name of the function is update-metadata and not write-newmetadata.

FYI: The original helper written couldn't add new meta data to the nuspec file. It would always throw an error.

If you insist on having those tests.i can work on them tomorrow.

**Comment by AdmiringWorm** [comment]
> I thought about adding those tests, but the name of the function is update-metadata and not write-newmetadata.

I am aware that it is called `update-metadata`, however an update in PowerShell can allow adding as well.

> FYI: The original helper written couldn't add new metadata to the nuspec file. It would always throw an error.

I am aware, initially, I wanted to allow the addition as well, but this created invalid metadata which is why I was forced to throw an exception if trying to add an item instead of updating it (if I remember correctly, two additional attributes would be added that caused choco pack failures).

> If you insist on having those tests.i can work on them tomorrow.

Since you don't do any error handling when updating files/dependencies, then yes, those tests are needed.
Either by throwing an error (same as usual metadata updates) or comparing with expected values if you want to allow it to happen.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Actually I did input those checks in the function earlier
For the [File check](https://github.com/RedBaron2/Wormies-AU-Helpers/blob/patch-2/Wormies-AU-Helpers/public/Update-Metadata.ps1#L74-L76)
For the [Dependency check](https://github.com/RedBaron2/Wormies-AU-Helpers/blob/patch-2/Wormies-AU-Helpers/public/Update-Metadata.ps1#L83-L85)
It is even in the new [tests](https://github.com/RedBaron2/Wormies-AU-Helpers/blob/patch-2/tests/public/Update-Metadata.Tests.ps1#L103-L106)

I wanted to ask your opinion about rewriting the following
`.DESCRIPTION
When a key and value is specified, update the package element with the specified key
and the corresponding value in the specified NuspecFile.
This will not add new elements to the nuspec file.

.PARAMETER key
The element that should be updated in the package section.
`
I can add the changes to the helper tomorrow. 😸

**Comment by AdmiringWorm** [comment]
> Actually I did input those checks in the function earlier
For the File check ( 15 minutes ago)
For the Dependency check ( 15 minutes ago)
It is even in the new tests ( 15 minutes ago)

That is not the same as why I am talking about.

Let us say you have the following in the nuspec file
```xml
<dependencies />
```
or
Maybe the `<dependencies>` are missing altogether.

And you call the update helper with
```powershell
Update-Metadata -key "dependency" -value "something.portable,2.2.4" # In this case, what will happen
```

Feel free to update the docs if you feel it would be better.

**Comment by AdmiringWorm** [comment]
Although, I don't think it is necessary the lack of adding support is necessary to be in the `.DESCRIPTION` section, as it is already in the `.NOTES` section: https://wormiecorp.github.io/Wormies-AU-Helpers/docs/functions/update-metadata#notes

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Gotcha I'll update these and work it in to the PR.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I'm going to close this PR and re-open a new PR Later.

Now that I know what is required for a PR of your helper. I will reorganize my files to make it easier the next time.

**Pull request closed without merging**
