### PR TITLE
(update-metadata.ps1) Adding File & Dependency with tests

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm 
This will add the ability to change Singular File & Dependency in nuspec package/metadata.
These are updated to be the same formatting as older files.
Update-Metadata function has been updated to use a switch instead of all the if and else statements which may increase the speed of the function

### CODE REVIEW

**Comment by RedBaron2** [comment]
I'll deal with the error tomorrow

**Comment by RedBaron2** [comment]
@AdmiringWorm 
All checks are green, and the tests do check for zero or multiple file/dependency in a nuspec file

**Comment by RedBaron2** [comment]
@AdmiringWorm 
I will be adjusting this to make it so multiples can be updated in the future.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Do you want this to add the node element; if not currently present in the nuspec file?

I really feel that would be a new function, but I can try to squeeze it into my additions to this one if needed.

New version so far will address 
- the multiples of file/dependency 
- add all attributes for the element
- specific attributes for the element

Still in development on a few issues, and how to write the tests.
Just keeping you in the loop

**Comment by AdmiringWorm** [comment]
> I really feel that would be a new function, but I can try to squeeze it into my additions to this one if needed.

An `Update-` cmdlet can add new items as well, but yeah I agree that it should perhaps be part of a new cmdlet instead.
At least, I don't believe it is worthwhile to look into adding that support right now.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
should I leave it to count lines like powershell `0..9` or normal `1..9`

**Comment by AdmiringWorm** [comment]
@RedBaron2 I am not sure if I follow. Could you expand upon what you are talking about?

**Comment by RedBaron2** [comment]
Powershell counts with 0 1 2 3 would equal 4
We normally count 1 2 3 4 to equal 4

**Comment by AdmiringWorm** [comment]
Yeah, I get that. That is pretty much programming 101. What I don't understand is the context of your question.
I don't see anywhere that you are using an index-based decision, so I don't get where you plan to use it.

But to try answering your question, if it is something that will be displayed to the user, then it should start on 1, otherwise use the standard 0 based index that is typically used in programming.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
It would be for the consumer to input for the multiple file/dependency to edit.

**Comment by RedBaron2** [comment]
@AdmiringWorm 
Would this be a problem
Updating a file/dependency key must have at least one attribute defined.
( EX: <file src="" /> -or- <dependency id="" /> )

**Comment by RedBaron2** [comment]
I'm going to close this PR and open another

**Pull request closed without merging**
